### ISSUE TITLE
大神你好，最新的知乎滑动到底部导航出现我想知道是如何实现的

### ISSUE THREAD

**Issue by twq8121108** [gdutxiaoxu/CoordinatorLayoutExample#1]
大神你好，最新的知乎滑动到底部导航出现我想知道是如何实现的

**Comment by gdutxiaoxu** [comment]
你可以阅读以下这篇博客，里面有讲到大概是怎么实现的，http://blog.csdn.net/gdutxiaoxu/article/details/53453958
