### ISSUE TITLE
向上滑动的时候 手机会一直震动，并且滑动有点卡顿

### ISSUE THREAD

**Issue by FZ985** [gdutxiaoxu/CoordinatorLayoutExample#10]

**Comment by FZ985** [comment]
微博发现页面的实现 例子
   向上滑动的时候有点卡顿，
   并且触摸recycleview列表向上滑动的时候， 会有手机一直振动(就像长按事件的那种震动)

**Comment by gdutxiaoxu** [comment]
最新代码没有发现该问题，请更新代码试试，如果还有该问题，请提供机型，系统
