### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by kscMaster** [gdutxiaoxu/CoordinatorLayoutExample#13]
我的需求是在fragment里使用coorlayout，进入时顶部一个Banner，滑动后Banner消失Toolbar显示，写在Aty里没问题，但是写在Fragment，状态栏就无法侵入了，请问怎么解决？

**Comment by gdutxiaoxu** [comment]
状态栏就无法侵入了？无法显示，还是沉浸式状态栏？

fragment 的布局贴一下， activity 的布局也贴一下

**Comment by gdutxiaoxu** [comment]
@957919019 状态栏就无法侵入了？无法显示，还是沉浸式状态栏？

fragment 的布局贴一下， activity 的布局也贴一下

**Comment by 957919019** [comment]
![111](https://user-images.githubusercontent.com/19183142/56490499-faed0000-6517-11e9-9cee-9500e210c9b3.gif)

这是Activity的布局
`<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context=".ui.MainActivity">

    <ViewPager
        android:id="@+id/vp_pager"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:fitsSystemWindows="true"
        app:layout_constraintBottom_toTopOf="@id/tl_tab"
        app:layout_constraintTop_toTopOf="parent" />

    <android.support.design.widget.TabLayout
        android:id="@+id/tl_tab"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="5dp"
        android:background="@android:color/white"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:tabGravity="fill"
        app:tabIndicatorColor="@color/colorPrimary"
        app:tabIndicatorHeight="2dp"
        app:tabMaxWidth="0dp"
        app:tabMode="fixed"
        app:tabSelectedTextColor="@color/colorPrimary"
        app:tabTextColor="#999" />

</android.support.constraint.ConstraintLayout>`

这是Fragment的布局，
`
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true" >

    <include layout="@layout/fg_hostel_view_toolbar"/>

    <android.support.v4.widget.NestedScrollView
        android:id="@+id/nsv_list"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <android.support.constraint.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <android.support.v7.widget.CardView
                android:id="@+id/cv_top"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="8dp"
                android:layout_marginLeft="10dp"
                android:layout_marginRight="10dp"
                android:elevation="8dp"
                app:cardCornerRadius="20dp"
                app:layout_constraintTop_toTopOf="parent">

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="vertical"
                    android:padding="10dp"
                    android:radius="10dp">

                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:orientation="horizontal">

                        <TextView
                            style="@style/HostelSearchHintStyle_title"
                            android:text="目的地" />

                        <TextView
                            android:id="@+id/tv_destination"
                            style="@style/HostelSearchHintStyle_right"
                            android:hint="请选择目的地" />
                    </LinearLayout>

                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:orientation="horizontal">

                        <TextView
                            style="@style/HostelSearchHintStyle_title"
                            android:text="我的位置" />

                        <TextView
                            android:id="@+id/tv_nearby"
                            style="@style/HostelSearchHintStyle_right"
                            android:hint="请选择我的位置" />
                    </LinearLayout>

                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:orientation="horizontal">

                        <TextView
                            style="@style/HostelSearchHintStyle_title"
                            android:text="最低价" />

                        <TextView
                            android:id="@+id/tv_lowPrice"
                            style="@style/HostelSearchHintStyle_right"
                            android:hint="点击选择价格区间" />
                    </LinearLayout>

                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:orientation="horizontal">

                        <TextView
                            style="@style/HostelSearchHintStyle_title"
                            android:text="最高价" />

                        <TextView
                            android:id="@+id/tv_highPrice"
                            style="@style/HostelSearchHintStyle_right"
                            android:hint="点击选择价格区间" />
                    </LinearLayout>

                    <LinearLayout
                        android:id="@+id/ll_reimbursement"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:orientation="horizontal"
                        android:visibility="gone">

                        <TextView
                            style="@style/HostelSearchHintStyle_title"
                            android:text="报销限额" />

                        <TextView
                            android:id="@+id/tv_reimbursement"
                            style="@style/HostelSearchHintStyle_right"
                            android:layout_marginRight="20dp"
                            android:drawableRight="@null" />
                    </LinearLayout>

                    <Button
                        android:id="@+id/bt_search"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginLeft="20dp"
                        android:layout_marginRight="20dp"
                        android:textColor="@color/white"
                        android:background="@drawable/bg_button_circle_green"
                        android:foreground="?attr/selectableItemBackgroundBorderless"
                        android:text="查找招待所宾馆" />

                    <TextView
                        android:id="@+id/tv_reset"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="right"
                        android:layout_marginRight="20dp"
                        android:foreground="?attr/selectableItemBackgroundBorderless"
                        android:padding="10dp"
                        android:text="重置筛选条件"  />
                </LinearLayout>
            </android.support.v7.widget.CardView>

            <TextView
                android:id="@+id/tv_hot"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_margin="8dp"
                android:text="关注热度排行"
                app:layout_constraintTop_toBottomOf="@id/cv_top" />

            <android.support.v7.widget.RecyclerView
                android:id="@+id/rv_hotList"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="8dp"
                app:fastScrollEnabled="false"
                app:layout_constraintTop_toBottomOf="@id/tv_hot"
                tools:listitem="@layout/item_hot_hostel" />
        </android.support.constraint.ConstraintLayout>
    </android.support.v4.widget.NestedScrollView>

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/bt_top"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="@dimen/fab_margin"
        android:theme="@style/green_style"
        app:elevation="12dp"
        app:fabSize="mini"
        app:layout_anchor="@id/nsv_list"
        app:layout_anchorGravity="bottom|end"
        app:layout_behavior="com.sby.heart.widget.ScrollAwareFABBehavior"
        app:pressedTranslationZ="30dp"
        app:rippleColor="@color/colorPrimaryDark"
        app:srcCompat="@mipmap/ic_top" />

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/bt_upload"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="16dp"
        android:theme="@style/green_style"
        app:elevation="12dp"
        app:layout_anchor="@id/abl_bar"
        app:layout_anchorGravity="bottom|end"
        app:pressedTranslationZ="30dp"
        app:srcCompat="@mipmap/ic_upload" />
</android.support.design.widget.CoordinatorLayout>
`


这里是Fragment的折叠Toolbar的布局，其中BGABanner是一个Banner，就是它，总是无法侵入状态栏，我写在Activity里是没问题的，只有Fragment出现这个问题
`<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.AppBarLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/abl_bar"
    android:layout_width="match_parent"
    android:layout_height="240dp"
    android:background="@color/transparent"
    android:fitsSystemWindows="true"
    android:theme="@style/AppTheme.AppBarOverlay">

    <android.support.design.widget.CollapsingToolbarLayout
        android:id="@+id/ctl_layoutbar"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fitsSystemWindows="true"
        app:contentScrim="?attr/colorPrimary"
        app:toolbarId="@+id/tb_toolbar"
        app:layout_scrollFlags="scroll|exitUntilCollapsed|snap">

        <cn.bingoogolapple.bgabanner.BGABanner
            android:id="@+id/bn_hostelBanner"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:fitsSystemWindows="true"
            app:banner_pointDrawable="@drawable/bga_banner_selector_point_solid"
            app:banner_transitionEffect="accordion" />

        <android.support.v7.widget.Toolbar
            android:id="@+id/tb_toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:elevation="10dp"
            app:contentInsetLeft="0dp"
            app:contentInsetStart="0dp"
            app:layout_collapseMode="pin">

            <include
                android:id="@+id/tb_toolbar1"
                layout="@layout/view_hostel_header_tb_title"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

            <include
                android:id="@+id/tb_toolbar2"
                layout="@layout/view_hostel_header_tb_title2"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:visibility="gone" />
        </android.support.v7.widget.Toolbar>

    </android.support.design.widget.CollapsingToolbarLayout>
</android.support.design.widget.AppBarLayout>`

我找了很多Demo，没见到几个在Fragment里侵入的，茫然，如果您能帮到我真是太好了

**Comment by 957919019** [comment]
我的主题，
`   <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>`

**Comment by gdutxiaoxu** [comment]
@957919019 加我 QQ 370851417，备注一下，我看一下，将 fragment  gif 图也发我一下
