### ISSUE TITLE
为什么下载项目每次都没有baselibrary的文件

### ISSUE THREAD

**Issue by Yihaoer** [gdutxiaoxu/CoordinatorLayoutExample#14]
为什么下载项目每次都没有baselibrary的文件

**Comment by gdutxiaoxu** [comment]
执行 git submodule init;git submodule update 即可下载

**Comment by Yihaoer** [comment]
> 执行 git submodule init;git submodule update 即可下载

我是直接下载项目 不是用git拉下来的 也可以这样吗
