### ISSUE TITLE
为什么我拉代码下来,BaseLibrary拉不下来?

### ISSUE THREAD

**Issue by luochune** [gdutxiaoxu/CoordinatorLayoutExample#15]
Cloning into '/Users/mac/.Trash/CoordinatorLayoutExample 下午10.57.30/AlipayHomeSample/CoordinatorLayoutExample/submodules/BaseLibrary'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by gdutxiaoxu** [comment]
你是不是没有将你本地的 ssh key 添加到 github 上面

**Comment by androidforme** [comment]
我也拉不下来。 这估计是个bug；作者能否检查下原因； 试了很多方式都是空文件夹

**Comment by gdutxiaoxu** [comment]
执行 git submodule init;git submodule update 即可下载

**Comment by gdutxiaoxu** [comment]
其他的 issue 已经说过了， 有问题可以先搜 issue https://github.com/gdutxiaoxu/CoordinatorLayoutExample/issues/14
