### ISSUE TITLE
ScaleDownShowBehavior 上滑时FloatActionButton无法显示

### ISSUE THREAD

**Issue by Sumsear** [gdutxiaoxu/CoordinatorLayoutExample#2]
我检查了一下楼主的代码，发现当FloatingActionButton的可见性为 GONE 的时候，onNestedScroll方法将不再调用，所以在动画监听的时候将View隐藏的话是不行的，应该在动画结束之后将FloatingActionButton的可见性设置为INVISIBLE

**Comment by Sumsear** [comment]
关于FloatingActionButton可见性为GONE之后为什么onNestedScroll方法不再调用可以查看我们查看CoordinatorLayout的源码，在源码的onNestedScroll方法中对子view的的可见性进行了判断，如果View可见性为GONE，直接continue了，下面的viewBehavior.onNestedScroll将没机会调用！！！

**Comment by gdutxiaoxu** [comment]
已修复
