### ISSUE TITLE
请问仿微博发现页demo中，我上滑后松开手能不自动吸顶吗，我想停留在原来的位置不变

### ISSUE THREAD

**Issue by shenyunmeng0519** [gdutxiaoxu/CoordinatorLayoutExample#6]

**Comment by gdutxiaoxu** [comment]
你可以在 WeiboHeaderPagerBehavior 中的 handleActionUp 进行处理，去除这一行  mFlingRunnable.scrollToClosed(DURATION_SHORT); 就不会自动吸顶
