### ISSUE TITLE
design库引用到25.3.1仿知乎tab的behavior失效

### ISSUE THREAD

**Issue by KaelInvoker** [gdutxiaoxu/CoordinatorLayoutExample#9]
如题

**Comment by gdutxiaoxu** [comment]
请问是在哪个 behavior 中，我修复一下

**Comment by KaelInvoker** [comment]
您好，我看的应该是之前的代码，现在用了最新的代码可以，不过体验上感觉和知乎很不一样。上上下下不间断反复滑动，知乎会随着手指的滑动view进行上下移动，而这里是View会停止不动。

**Comment by KaelInvoker** [comment]
您好，是在FooterBehavior

**Comment by gdutxiaoxu** [comment]
上上下下的那个已修复，效果的根据项目需要调整
